[tool.poetry]
name = "v3"
version = "0.1.0"
description = ""
authors = ["Claudio"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^5.4"
fastapi = "^0.54.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
